---
title: "Visualization of Drug Classes and Target Genes"
author: "Lisa Holsten"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(xlsx)
library(dplyr)
library(tidyverse)
library(tidyr)
library(reshape2)
library(stringi)
library(stringr)
library(ggplot2)
library(RColorBrewer)
library(pals)
library(unikn)
library(htmlwidgets)
library(ggwordcloud)
library(wordcloud)
library(wordcloud2)
```

# Load current drug list
```{r}
DrugList <- read.xlsx(file = "Druglist_CovidTrials.xlsx", sheetIndex = 1, stringsAsFactors = FALSE)
```

# Drug Classes
## Colors
```{r}
colors.classes <- colorRampPalette(unikn::pal_unikn_pair)(17)
colors.classes <- colors.classes[c(1:3, 5:17)]
```

## Calculation of Number of Drugs and Number of Clinical Trials
```{r}
# Adaption of DrugList for visualization
Covid_drugs <- DrugList %>% rename("Category" = Classes_for_visualization)

# Number of drugs / class
Covid_drugs <- Covid_drugs %>% separate_rows(Category, sep = ", ")
Covid_drugs[Covid_drugs$Category == "Antifungals", "Category"] <- "Other"
  
drug_classes <- Covid_drugs %>%
  group_by(Category) %>%
  summarise(sum = n()) %>%
  mutate(freq = sum/ sum(sum))


# Number of clinical trials / class
## Subset for relevant columns
Drugs_ClinicalTrials <- Covid_drugs %>% select(Drug, NCT.Number, Category) %>% separate_rows(NCT.Number, sep = ", ")

## One column per NCT.Number
tmp <- lapply(unique(Drugs_ClinicalTrials$NCT.Number), function(x) {
  tmp2 <- Drugs_ClinicalTrials[Drugs_ClinicalTrials$NCT.Number == x, ]
  tmp_new <- data.frame(NCT.Number = x,
                        Drugs = paste(unique(tmp2$Drug), collapse = ", "),
                        Category = paste(unique(tmp2$Category), collapse = ", "),
                        stringsAsFactors = F)
  tmp_new
})

Drugs_ClinicalTrials <- bind_rows(tmp)

## Split into rows for each category and remove NA rows
Drugs_ClinicalTrials <- Drugs_ClinicalTrials %>% separate_rows(Category, sep = ", ")
Drugs_ClinicalTrials <- Drugs_ClinicalTrials[Drugs_ClinicalTrials$Category != "NA", ]

## Calculate number of clinical trials / class
drug_trials <- Drugs_ClinicalTrials %>%
  group_by(Category) %>%
  summarise(sum = n()) %>%
  mutate(freq = sum/ sum(sum))


# Combine both data frames
drug_merged <- bind_rows(drug_trials, drug_classes, .id = "Comparison")
drug_merged[1:16, "Comparison"] <- "NumberOfClinicalTrials"
drug_merged[17:32, "Comparison" ] <- "NumberOfDrugs"

# Reorder factor levels
levels <- c("Anti-inflammatory agents", "Immunosuppressants", "Immunostimulants",
            "Antibacterials", "Antiparasitics", "Antiseptics", "Antivirals",
            "Antineoplastic agents",
            "Antifibrinolytics", "Antihemorrhagic agents", "Antithrombotic agents", 
            "Cardiovascular system", "Nervous system", "Respiratory system", "Vaccine",
            "Other")
levels.reverse <- rev(levels)

drug_merged$Category <- factor(drug_merged$Category, 
                                 levels = levels)

```

## Donut Plot
```{r, fig.height=8, fig.width=12}
ggplot(drug_merged, aes(x = Comparison, y = freq, fill = Category, color = Comparison)) + 
  geom_col(size = 0.5) + 
  scale_color_manual(values = c("black", "darkgrey")) + 
  scale_x_discrete(limits = c(" ", "NumberOfDrugs", "NumberOfClinicalTrials")) +
  geom_text(aes(label = sum), position = position_stack(vjust = 0.5), color = "white") +
  scale_fill_manual(values = colors.classes) +
  coord_polar("y") +
  theme_void() 

Donut <- ggplot(drug_merged, aes(x = Comparison, y = freq, fill = Category, color = Comparison)) + 
  geom_col(size = 0.5) + 
  scale_color_manual(values = c("black", "darkgrey")) + 
  scale_x_discrete(limits = c(" ", "NumberOfDrugs", "NumberOfClinicalTrials")) +
  geom_text(aes(label = sum), position = position_stack(vjust = 0.5), color = "white") +
  scale_fill_manual(values = colors.classes) +
  coord_polar("y") +
  theme_void()

cairo_pdf(filename = "DonutPlot.pdf", width = 12, height = 8)
plot(Donut)
dev.off()
```



# Target Genes
## Prepare data frame
```{r}
TargetGenes <- DrugList$Target.Gene[!is.na(DrugList$Target.Gene)]
TargetGenes <- unlist(as.vector(str_split(string = TargetGenes, pattern = ", ", n = Inf)))
TargetGenes <- TargetGenes[TargetGenes != ""]
TargetGenes <- TargetGenes[TargetGenes != " "]

# Coerce to dataframe and Clean-up
wordcloud_df <- as.data.frame(TargetGenes, stringsAsFactors = F)
wordcloud_df[wordcloud_df$TargetGenes == "L (Zaire ebolavirus)", "TargetGenes"] <- "L"
wordcloud_df[wordcloud_df$TargetGenes == "\nL", "TargetGenes"] <- "L"
wordcloud_df[wordcloud_df$TargetGenes == " HSPA5", "TargetGenes"] <- "HSPA5"
wordcloud_df[wordcloud_df$TargetGenes == "\nEDNRB", "TargetGenes"] <- "EDNRB"
wordcloud_df[wordcloud_df$TargetGenes == "\nMCFD2", "TargetGenes"] <- "MCFD2"

# Calculate number of occurances
wordcloud_df <- wordcloud_df %>%
  rename("Target" = TargetGenes) %>%
  group_by(Target) %>%
  summarize(freq= n())
```

## Wordcloud
```{r, fig.height = 13, fig.width=10}
colors.targets <- rev(colors.classes)[6:16]

wordcloud(words = wordcloud_df$Target, freq = wordcloud_df$freq, min.freq = 4, max.words = 400, random.order = FALSE, 
          rot.per = 0.5, scale = c(6.5,2), colors = colors.targets, random.color = F)
```

